/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pegawai;

import Config.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Iqbal
 */
public class Menu_Pengajuan extends javax.swing.JFrame {
    
    koneksi db = new koneksi();
    
    protected String _query;
    public String id_pengguna, id_kategori, nama_kategori, no_rekening;
    protected Boolean _is_grant = false;

    /**
     * Creates new form Pengajuan_Pembelian_Perlengkapan
     */
    public Menu_Pengajuan() {
        initComponents();
        this.enabled_form(false);
        
        b_input_lagi.setEnabled(false);
        b_hapus.setEnabled(false);
        b_selesai.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        f_id_pengguna = new javax.swing.JTextField();
        f_id_pengajuan = new javax.swing.JTextField();
        f_tanggal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        f_id_kategori = new javax.swing.JTextField();
        f_nama_kategori = new javax.swing.JTextField();
        f_no_kategori = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        f_jumlah = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_keterangan = new javax.swing.JTextArea();
        b_cari_barang = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        c_unit = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        b_process = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        f_mulai = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        f_akhir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_data = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        c_status_filter = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t_data_sementara = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        b_input_lagi = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        b_selesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI KAS KACIL - PT. Exlayer Teknologi Indonesia | Pengajuan Pembelian Perlengkapan");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(2, 47, 102));

        jPanel2.setBackground(new java.awt.Color(2, 47, 102));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pengajuan Pengeluaran Kas Kecil");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aplikasi Kas Kecil");

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PT. Exlayer Teknologi Indonesia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4))
        );

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(2, 47, 102));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Pengguna");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID Pengajuan");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(f_id_pengguna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(f_tanggal)
                    .addComponent(f_id_pengajuan))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(f_id_pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(f_id_pengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(f_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(2, 47, 102));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Kategori");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama Kategori");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("No Kategori");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jumlah");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Keterangan");

        ta_keterangan.setColumns(20);
        ta_keterangan.setRows(5);
        jScrollPane1.setViewportView(ta_keterangan);

        b_cari_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_search_18pt.png"))); // NOI18N
        b_cari_barang.setText("Cari");
        b_cari_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cari_barangActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Unit");

        c_unit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "Pcs", "Lembar" }));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pengajuan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f_nama_kategori, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(f_no_kategori)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(f_id_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_cari_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(c_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(f_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(f_id_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(f_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cari_barang)
                    .addComponent(jLabel11)
                    .addComponent(c_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(f_nama_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(f_no_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel15))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        b_process.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_save_18pt.png"))); // NOI18N
        b_process.setText("Buat Baru");
        b_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_processActionPerformed(evt);
            }
        });

        b_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_clear_18pt.png"))); // NOI18N
        b_cancel.setText("Keluar");
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(2, 47, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null), "Data Pengajuan & Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Filter data pengajuan mulai dari ");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("sampai");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_autorenew_18pt.png"))); // NOI18N
        jButton1.setText("Process");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        t_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_dataMouseClicked(evt);
            }
        });
        t_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_dataKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(t_data);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Atau Filter dengan status");

        c_status_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "Belum Di Setujui", "Telah Di Setujui" }));
        c_status_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_status_filterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f_mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(f_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(c_status_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(f_mulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(f_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel22)
                    .addComponent(c_status_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(2, 47, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null), "Detail Pengajuan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        t_data_sementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(t_data_sementara);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("*Note : Tekan Tombol ' DELETE' untuk menghapus data");

        jPanel7.setBackground(new java.awt.Color(2, 47, 102));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_map_white_18pt.png"))); // NOI18N
        jLabel23.setText("Alamat");

        jLabel24.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Intiland Tower - Annex, 8th Floor. Jl. Jend. Sudirman Kav 32, Jakarta 10220");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_phone_white_18pt.png"))); // NOI18N
        jLabel25.setText("Telepon");

        jLabel26.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("(021) -57853468 ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(12, 12, 12)
                .addComponent(jLabel25)
                .addGap(10, 10, 10)
                .addComponent(jLabel26))
        );

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xlayer_logo.jpg"))); // NOI18N

        b_input_lagi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_autorenew_18pt.png"))); // NOI18N
        b_input_lagi.setText("Input Lagi");
        b_input_lagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_input_lagiActionPerformed(evt);
            }
        });

        b_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_clear_18pt.png"))); // NOI18N
        b_hapus.setText("Hapus");
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });

        b_selesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_save_18pt.png"))); // NOI18N
        b_selesai.setText("Selesai");
        b_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_selesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_process, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_selesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_hapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_input_lagi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(b_process, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b_input_lagi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.check_permission();
        this.get_data_table(); this.get_data_sementara();
        f_tanggal.setText(koneksi.get_date_with_format("YYYY-MM-dd"));
        f_id_pengguna.setEditable(false);
    }//GEN-LAST:event_formWindowActivated

    private void b_cari_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cari_barangActionPerformed
        Menu_Popup_Kategori portal = new Menu_Popup_Kategori();
        portal.grant_permission(true);
        portal.portal = this;
        portal.setVisible(true);
    }//GEN-LAST:event_b_cari_barangActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        f_id_kategori.setText(this.id_kategori);
        f_nama_kategori.setText(this.nama_kategori);
        f_no_kategori.setText(this.no_rekening);
        if("502".equals(f_no_kategori.getText())){
            f_jumlah.setEnabled(false);
            c_unit.setEnabled(false);
            f_jumlah.setText(null);
            c_unit.setSelectedIndex(0);
        } else if ("511".equals(f_no_kategori.getText())) {
            f_jumlah.setEnabled(true);
            c_unit.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void b_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_processActionPerformed
        switch (b_process.getText()){
            case "Buat Baru":
                this.create_new_pengajuan();
                this.save_pengajuan();
                this.enabled_form(true);
                b_process.setText("Simpan");
                b_cancel.setText("Batal");
                
                b_input_lagi.setEnabled(true);
                b_hapus.setEnabled(true);
                b_selesai.setEnabled(true);
            break;
            case "Simpan":
                if(this.field_validation()){
                    this.save_pengajuan_sementara();
                    b_process.setEnabled(false);
                    this.enabled_form(false);
                    this.clear();
                    b_cancel.setText("Keluar");
                    b_input_lagi.setText("Input Lagi");
                    this.get_data_table();
                    this.get_data_sementara();
                }
            break;
        }
    }//GEN-LAST:event_b_processActionPerformed

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        switch (b_cancel.getText()){
            case "Batal":
                int konfir = JOptionPane.showConfirmDialog(this, 
                    "Apa Anda Yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            
                if (konfir == JOptionPane.YES_OPTION){

                    try {
                        db.runQueryUpdate("DELETE FROM pengajuan WHERE id_pengajuan = '"+ f_id_pengajuan.getText() +"'");
                        koneksi.popup_message("Berhasil di hapus!");
                    } catch (SQLException err) {koneksi.print(err.getMessage());}

                }
                this.clear();
                this.enabled_form(false);
                b_cancel.setText("Keluar"); f_id_pengajuan.setText(null);
            break;
            case "Keluar":
                this.dispose();
            break;
            case "Kembali":
                t_data.clearSelection();
                t_data_sementara.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {},
                    new String [] {"No Kategori", "Nama Kategori", "Unit", "Jumlah", "Keterangan"}
                ));
                f_id_pengajuan.setText(null);
                b_cancel.setText("Keluar");
                b_hapus.setText("Hapus");
                break;
        }
    }//GEN-LAST:event_b_cancelActionPerformed

    private void t_dataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_dataKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE){
            int konfir = JOptionPane.showConfirmDialog(this, 
                    "Apa Anda Yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            
            if (konfir == JOptionPane.YES_OPTION){
                
                try {
                    db.runQueryUpdate("DELETE FROM pengajuan WHERE id_pengajuan = '"+ f_id_pengajuan.getText() +"'");
                    koneksi.popup_message("Berhasil di hapus!");
                } catch (SQLException err) {koneksi.print(err.getMessage());}
                
            }
            b_process.setText("Buat Baru");
            f_id_pengajuan.setText(null);
            
            b_input_lagi.setEnabled(false);
            b_hapus.setEnabled(false);
            b_selesai.setEnabled(false);
        }
    }//GEN-LAST:event_t_dataKeyPressed

    private void t_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_dataMouseClicked
        f_id_pengajuan.setText((String) t_data.getValueAt(t_data.getSelectedRow(), 0));
        
        final String[] _label = {"No Kategori", "Nama Kategori", "Unit", "Jumlah", "Keterangan"};
        try {
            ResultSet result = db.runQuery("SELECT no_kategori, nama_kategori, unit, jumlah, "
                                         + "keterangan_pengajuan FROM detail_pengajuan WHERE id_pengajuan = '"+f_id_pengajuan.getText()+"'");
            
            ResultSetMetaData table = result.getMetaData();
            int _row = 0, counter = 0; while(result.next()) _row = result.getRow();
            
            Object[][] _data = new Object[_row][table.getColumnCount()];
            result.beforeFirst();
            
            while(result.next()){
                
                for(int i = 0; i < table.getColumnCount(); i++) _data[counter][i] = result.getString(i+1);
                counter++;
                
            }
            
            t_data_sementara.setModel(new javax.swing.table.DefaultTableModel(_data, _label));
            
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
        b_cancel.setText("Kembali"); b_hapus.setText("Hapus Detail");
        b_process.setText("Simpan");
        this.enabled_form(false);
        
        b_input_lagi.setEnabled(true);
        b_hapus.setEnabled(true);
        b_selesai.setEnabled(true);
    }//GEN-LAST:event_t_dataMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(f_mulai.getText().isEmpty() && f_akhir.getText().isEmpty()){
            koneksi.popup_message("Data belum lengkap!");
            this.get_data_table();
        } else {
            this.get_data_table_filtered();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c_status_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_status_filterActionPerformed
        if(c_status_filter.getSelectedIndex() > 0){
            final String[] _label = {"ID Pengajuan", "ID Pengguna", "Tanggal Pengajuan", "Status"};
            try {
                ResultSet result = db.runQuery("SELECT id_pengajuan, id_pengguna, tanggal_pengajuan, "
                                             + "status FROM pengajuan WHERE status = '"+c_status_filter.getSelectedItem()+"' "
                                             + " AND id_pengguna = '"+f_id_pengguna.getText()+"'");
                
                ResultSetMetaData table = result.getMetaData();
                int _row = 0, counter = 0; while(result.next()) _row = result.getRow();

                Object[][] _data = new Object[_row][table.getColumnCount()];
                result.beforeFirst();

                while(result.next()){

                    for(int i = 0; i < table.getColumnCount(); i++) _data[counter][i] = result.getString(i+1);
                    counter++;

                }

                t_data.setModel(new javax.swing.table.DefaultTableModel(_data, _label));

            } catch (SQLException err) { koneksi.print(err.getMessage()); }
        }
    }//GEN-LAST:event_c_status_filterActionPerformed

    private void b_input_lagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_input_lagiActionPerformed
        switch(b_input_lagi.getText()){
            case "Input Lagi":
                b_input_lagi.setText("Batalkan");
                this.enabled_form(true);
                b_process.setEnabled(true);
                break;
            case "Batalkan":
                this.clear();
                this.enabled_form(false);
                b_input_lagi.setText("Input Lagi");
                break;
        }
        
    }//GEN-LAST:event_b_input_lagiActionPerformed

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        String nama_kategori = (String) t_data_sementara.getValueAt(t_data_sementara.getSelectedRow(), 1);
        
        int konfir = JOptionPane.showConfirmDialog(this, 
                    "Apa Anda Yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            
        if (konfir == JOptionPane.YES_OPTION){

            try {
                if(b_hapus.getText().equals("Hapus Detail")){
                    
                    db.runQueryUpdate("DELETE FROM detail_pengajuan WHERE id_pengajuan = '"+f_id_pengajuan.getText()+"' AND "
                                + "id_pengguna = '"+f_id_pengguna.getText()+"' AND nama_kategori = '"+nama_kategori+"'");
                    b_hapus.setText("Hapus");
                
                } else {
                    
                    db.runQueryUpdate("DELETE FROM pengajuan_sementara WHERE id_pengajuan = '"+f_id_pengajuan.getText()+"' AND "
                                + "id_pengguna = '"+f_id_pengguna.getText()+"' AND nama_kategori = '"+nama_kategori+"'");
                    
                }
                
                koneksi.popup_message("Berhasil di hapus!");
                t_data_sementara.clearSelection();
            } catch (SQLException err) {koneksi.print(err.getMessage());}
            
             b_input_lagi.setEnabled(false);
            b_hapus.setEnabled(false);
            b_selesai.setEnabled(false);

        }
    }//GEN-LAST:event_b_hapusActionPerformed

    private void b_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_selesaiActionPerformed
        for(int i = 0; i < t_data_sementara.getRowCount(); i++){
            this._query = "INSERT INTO detail_pengajuan (id_pengajuan, id_pengguna, no_kategori, "
                    + " nama_kategori, unit, jumlah, keterangan_pengajuan) VALUES ('"
                    + f_id_pengajuan.getText() + "', '"+ f_id_pengguna.getText()+"', '"
                    + (String) t_data_sementara.getValueAt(i, 0) +"', '"+ (String) t_data_sementara.getValueAt(i, 1) +"', "
                    + "'"+ (String) t_data_sementara.getValueAt(i, 2) +"', "+ (String) t_data_sementara.getValueAt(i, 3) +", '"
                    + (String) t_data_sementara.getValueAt(i, 4) + "')";
            try {
                db.runQueryUpdate(_query);
                db.runQueryUpdate("DELETE FROM pengajuan_sementara WHERE id_pengajuan = '"+f_id_pengajuan.getText()+"'");
            } catch (SQLException err) { koneksi.print(err.getMessage()); }
        }
        b_process.setText("Buat Baru"); f_id_pengajuan.setText(null); b_process.setEnabled(true); b_hapus.setText("Hapus");
        koneksi.popup_message("Berhasil di simpan");
        
        b_input_lagi.setEnabled(false);
        b_hapus.setEnabled(false);
        b_selesai.setEnabled(false);
    }//GEN-LAST:event_b_selesaiActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Pengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Menu_Pengajuan portal = new Menu_Pengajuan();
            portal.setLocationRelativeTo(null);
            portal.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_cari_barang;
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_input_lagi;
    private javax.swing.JButton b_process;
    private javax.swing.JButton b_selesai;
    private javax.swing.JComboBox<String> c_status_filter;
    private javax.swing.JComboBox<String> c_unit;
    private javax.swing.JTextField f_akhir;
    private javax.swing.JTextField f_id_kategori;
    private javax.swing.JTextField f_id_pengajuan;
    private javax.swing.JTextField f_id_pengguna;
    private javax.swing.JTextField f_jumlah;
    private javax.swing.JTextField f_mulai;
    private javax.swing.JTextField f_nama_kategori;
    private javax.swing.JTextField f_no_kategori;
    private javax.swing.JTextField f_tanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable t_data;
    private javax.swing.JTable t_data_sementara;
    private javax.swing.JTextArea ta_keterangan;
    // End of variables declaration//GEN-END:variables
        
    
    // PUBLIC CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    public void set_user(String _id_pengguna, String _name){
        f_id_pengguna.setText(_id_pengguna);
        this.id_pengguna = _id_pengguna;
    }
    
    //---------------------------------------------------------------------------------//
    
    public void grant_permission(Boolean _grant){
        this._is_grant = _grant;
    }
    
    
    
    // PROTECTED CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    protected void check_permission(){
        if(this._is_grant.equals(false)) {
            koneksi.popup_message("Anda tidak memiliki izin!");
            this.dispose();
        }
    }    
    
    
    
    
    // PRIVATE CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    private void create_new_pengajuan(){
        this._query = "SELECT id_pengajuan FROM pengajuan ORDER BY id_pengajuan DESC LIMIT 1";
        try {
            
            ResultSet id = db.runQuery(_query);
            if(id.next()){
                int no_urut = Integer.parseInt(id.getString(1).split("/")[3]) + 1;
                f_id_pengajuan.setText("PJN"+koneksi.get_date_with_format("/YY/MM/"+no_urut));
            }
            else f_id_pengajuan.setText("PJN"+koneksi.get_date_with_format("/YY/MM/1"));
            db.runQueryUpdate("INSERT INTO pengajuan(id_pengajuan) VALUES ('"+f_id_pengajuan.getText()+"')");
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
        
    }
        
    //---------------------------------------------------------------------------------//
    
    private void save_pengajuan(){
        this._query = "UPDATE pengajuan SET "
                    + "id_pengguna = '"+ f_id_pengguna.getText() +"', "
                    + "tanggal_pengajuan = '"+ f_tanggal.getText() +"' "
                    + "WHERE id_pengajuan = '"+f_id_pengajuan.getText()+"'";
        try {
            
            db.runQueryUpdate(_query);
            this.get_data_table();
            
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
        
        this.clear();
    }
    
    //---------------------------------------------------------------------------------//
    
    private void save_pengajuan_sementara(){
        String unit = (String) c_unit.getSelectedItem(),
               jumlah = f_jumlah.getText();
        if (c_unit.getSelectedIndex() == 0 ) unit = " - ";
        if (f_jumlah.getText().isEmpty()) jumlah = "0";
        
        this._query = "INSERT INTO pengajuan_sementara(id_pengajuan, id_pengguna, no_kategori, "
                    + " nama_kategori, unit, jumlah, keterangan_pengajuan) VALUES ('"
                    + f_id_pengajuan.getText() + "', '"+ f_id_pengguna.getText()+"', '"
                    + f_no_kategori.getText() +"', '"+ f_nama_kategori.getText() +"', '"+ unit +"', "
                    + jumlah +", '"+ta_keterangan.getText() + "')";
        try {
            db.runQueryUpdate(_query);
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
    }
    
    //---------------------------------------------------------------------------------//
    
    private void get_data_table(){
        final String[] _label = {"ID Pengajuan", "ID Pengguna", "Tanggal Pengajuan", "Status"};
        try {
            ResultSet result = db.runQuery("SELECT id_pengajuan, id_pengguna, tanggal_pengajuan, "
                                         + "status FROM pengajuan WHERE id_pengguna = '"+f_id_pengguna.getText()+"'");
            ResultSetMetaData table = result.getMetaData();
            int _row = 0, counter = 0; while(result.next()) _row = result.getRow();
            
            Object[][] _data = new Object[_row][table.getColumnCount()];
            result.beforeFirst();
            
            while(result.next()){
                
                for(int i = 0; i < table.getColumnCount(); i++) _data[counter][i] = result.getString(i+1);
                counter++;
                
            }
            
            t_data.setModel(new javax.swing.table.DefaultTableModel(_data, _label));
            
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
    }
    
    //---------------------------------------------------------------------------------//
    
    private void get_data_table_filtered(){
        String _akhir = f_akhir.getText(), _awal = f_mulai.getText();
        if(_akhir.isEmpty()) _akhir = f_mulai.getText();
        if(_awal.isEmpty()) _awal = koneksi.get_date_with_format("YYYY-MM-dd");
        final String[] _label = {"ID Pengajuan", "ID Pengguna", "Tanggal Pengajuan", "Status"};
        try {
            
            ResultSet result = db.runQuery("SELECT id_pengajuan, id_pengguna, tanggal_pengajuan, "
                                         + "status FROM pengajuan WHERE tanggal_pengajuan BETWEEN "
                                         + "'"+_awal+"' AND '"+_akhir+"' AND id_pengguna = '"+f_id_pengguna.getText()+"'");
            
            ResultSetMetaData table = result.getMetaData();
            int _row = 0, counter = 0; while(result.next()) _row = result.getRow();
            
            Object[][] _data = new Object[_row][table.getColumnCount()];
            result.beforeFirst();
            
            while(result.next()){
                
                for(int i = 0; i < table.getColumnCount(); i++) _data[counter][i] = result.getString(i+1);
                counter++;
                
            }
            
            t_data.setModel(new javax.swing.table.DefaultTableModel(_data, _label));
            
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
    }
    
    //---------------------------------------------------------------------------------//
    
    private void get_data_sementara(){
        final String[] _label = {"No Kategori", "Nama Kategori", "Unit", "Jumlah", "Keterangan"};
        try {
            ResultSet result = db.runQuery("SELECT no_kategori, nama_kategori, unit, jumlah, "
                                         + "keterangan_pengajuan FROM pengajuan_sementara");
            
            ResultSetMetaData table = result.getMetaData();
            int _row = 0, counter = 0; while(result.next()) _row = result.getRow();
            
            Object[][] _data = new Object[_row][table.getColumnCount()];
            result.beforeFirst();
            
            while(result.next()){
                
                for(int i = 0; i < table.getColumnCount(); i++) _data[counter][i] = result.getString(i+1);
                counter++;
                
            }
            
            t_data_sementara.setModel(new javax.swing.table.DefaultTableModel(_data, _label));
            
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
    }
        
    //---------------------------------------------------------------------------------//
    
    private void clear(){
        this.id_kategori = null; this.nama_kategori = null; no_rekening = null;
        f_id_kategori.setText(null); f_nama_kategori.setText(null); f_no_kategori.setText(null);
        c_unit.setSelectedIndex(0); f_jumlah.setText(null); ta_keterangan.setText(null);
    }
    
    //---------------------------------------------------------------------------------//
    
    private void enabled_form(Boolean _status){
        f_id_kategori.setEnabled(_status); f_nama_kategori.setEnabled(_status); f_no_kategori.setEnabled(_status);
        c_unit.setEnabled(_status); ta_keterangan.setEnabled(_status); b_cari_barang.setEnabled(_status);
        f_jumlah.setEnabled(_status);
    }
    
    //---------------------------------------------------------------------------------//
    
    private Boolean field_validation(){
        javax.swing.JTextField[] _fields = {f_id_kategori, f_no_kategori, f_nama_kategori};
        for(javax.swing.JTextField _field : _fields){
            if(_field.getText().isEmpty() && ta_keterangan.getText().isEmpty()){
                koneksi.popup_message("Data Belum lengkap");
                return false;
            }
        }
        return true;
    }
    
    
    
    // END OF CLASS DECLARATION
}
