/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Config.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Iqbal
 */
public class Menu_Pengguna extends javax.swing.JDialog {
    
    koneksi db = new koneksi();
    
    protected Boolean _is_grant = false, _delete = true;
    protected String _query, _user, _pass_lama;
    
    /**
     * Creates new form User
     */
    public Menu_Pengguna() {
        initComponents();
        l_ket.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        f_username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c_jabatan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        f_password = new javax.swing.JPasswordField();
        f_password_verify = new javax.swing.JPasswordField();
        l_pass_1 = new javax.swing.JLabel();
        l_pass_2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        b_process = new javax.swing.JButton();
        b_batal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_data = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        f_cari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        f_nama = new javax.swing.JTextField();
        f_id_pengguna = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        l_ket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("APLIKASI KAS KACIL - PT. Exlayer Teknologi Indonesia | Manajemen Pengguna");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(2, 47, 102));

        jPanel2.setBackground(new java.awt.Color(2, 47, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xlayer_logo.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Manajemen Pengguna");

        jSeparator1.setBackground(new java.awt.Color(2, 47, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("PT. Exlayer Teknologi Indonesia");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Aplikasi Kas Kecil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");

        c_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pegawai", "Admin", "Keuangan" }));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ENTER");

        f_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_passwordActionPerformed(evt);
            }
        });

        l_pass_1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l_pass_1.setForeground(new java.awt.Color(255, 255, 255));
        l_pass_1.setText("Password");

        l_pass_2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l_pass_2.setForeground(new java.awt.Color(255, 255, 255));
        l_pass_2.setText("Verifikasi Password");

        jPanel3.setBackground(new java.awt.Color(2, 47, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null), "Action Panel", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        b_process.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_save_18pt.png"))); // NOI18N
        b_process.setText("Simpan");
        b_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_processActionPerformed(evt);
            }
        });

        b_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_clear_18pt.png"))); // NOI18N
        b_batal.setText("Batal");
        b_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_process, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_process, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(2, 47, 102));

        t_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_dataMouseClicked(evt);
            }
        });
        t_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_dataKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(t_data);

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cari Akun Pengguna");

        f_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                f_cariKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("*Note : Tekan tombol ' DELETE'  di keyboard untuk menghapus data");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f_cari))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(f_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama Lengkap");

        f_id_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_id_penggunaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID pengguna");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jabatan");

        l_ket.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        l_ket.setForeground(new java.awt.Color(255, 255, 255));
        l_ket.setText("( Optional )");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(f_password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_ket, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(f_password_verify, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(128, 128, 128))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(f_nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(f_id_pengguna)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(l_pass_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_jabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f_username)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(l_pass_2)
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f_id_pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_pass_1)
                    .addComponent(l_pass_2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_password_verify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_ket))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        f_username.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this._check_permission();
        this.get_data_table();
    }//GEN-LAST:event_formWindowActivated

    private void f_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_cariKeyTyped
        this.search_data_table();
    }//GEN-LAST:event_f_cariKeyTyped

    private void b_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_processActionPerformed
        if(this.field_validation()){
            if(l_pass_2.getText().equals("Password Baru") && f_password.getText().equals(f_password_verify.getText())){
                koneksi.popup_message("Password baru sama dengan password lama!");
            } else {
                switch(b_process.getText()){
                    case "Simpan":
                        if(f_password.getText().equals(f_password_verify.getText())){
                            this.create_user();
                            f_id_pengguna.setEnabled(true); f_id_pengguna.setText(null);
                        } else koneksi.popup_message("Password verifikasi tidak sama!");
                        break;
                    case "Simpan Perubahan":
                        this.update_user();
                        f_id_pengguna.setEnabled(true); f_id_pengguna.setText(null);
                        b_process.setText("Simpan"); f_username.setEnabled(true);
                        f_password.setEnabled(true); l_pass_1.setText("Password");
                        this._pass_lama = null; l_ket.setVisible(false);
                        break;
                }
                this.get_data_table();
                f_username.setText(null); c_jabatan.setSelectedIndex(0); f_nama.setText(null);
                f_password.setText(null); f_password_verify.setText(null); 
            }
        }
    }//GEN-LAST:event_b_processActionPerformed

    private void b_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_batalActionPerformed
        f_username.setText(null); c_jabatan.setSelectedIndex(0); f_nama.setText(null);
        f_password.setText(null); f_password_verify.setText(null); f_id_pengguna.setText(null);
        b_process.setText("Simpan"); f_username.setEnabled(true); f_id_pengguna.setEnabled(true);
        c_jabatan.setEnabled(true); l_pass_1.setText("Password"); l_ket.setVisible(false);
        t_data.clearSelection(); this._pass_lama = null; f_password.setEnabled(true);
    }//GEN-LAST:event_b_batalActionPerformed

    private void t_dataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_dataKeyPressed
        String username = (String) t_data.getValueAt(t_data.getSelectedRow(), 0);
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE){
            if(this._delete){
                int konfir = JOptionPane.showConfirmDialog(this, 
                        "Apa Anda Yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

                if (konfir == JOptionPane.YES_OPTION){

                    try {
                        db.runQueryUpdate("DELETE FROM pengguna WHERE id_pengguna = '"+username+"'");
                        koneksi.popup_message("'"+username+"' berhasil di hapus!");
                    } catch (SQLException err) {koneksi.print(err.getMessage());}
                }
            } else koneksi.popup_message("Hanya terdapat 1 admin tidak dapat di hapus");
            
            l_pass_1.setText("Password"); l_ket.setVisible(false);
            f_username.setText(null); c_jabatan.setSelectedIndex(0); f_nama.setText(null);
            f_password.setText(null); f_password_verify.setText(null); f_id_pengguna.setText(null);
            b_process.setText("Simpan"); f_id_pengguna.setEnabled(true); c_jabatan.setEnabled(true);
        }
    }//GEN-LAST:event_t_dataKeyPressed

    private void t_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_dataMouseClicked
        b_process.setText("Simpan Perubahan");
        f_id_pengguna.setEnabled(false);
        l_pass_1.setText("Ganti Password Lama"); l_ket.setVisible(true);
        try{
            ResultSet check = db.runQuery("SELECT COUNT(jabatan) FROM pengguna WHERE jabatan = 'Admin'");
            if(check.next()){
                if(check.getInt(1) == 1 && t_data.getValueAt(t_data.getSelectedRow(), 4).equals("Admin")){
                    c_jabatan.setEnabled(false);
                    this._delete = false;
                } else {
                    this._delete = true;
                    c_jabatan.setEnabled(true);
                }
            }
        } catch (SQLException err) {koneksi.print(err.getMessage());}
        f_id_pengguna.setText((String) t_data.getValueAt(t_data.getSelectedRow(), 0));
        f_username.setText((String) t_data.getValueAt(t_data.getSelectedRow(), 1));
        c_jabatan.setSelectedItem((String) t_data.getValueAt(t_data.getSelectedRow(), 4));
        f_nama.setText((String) t_data.getValueAt(t_data.getSelectedRow(), 2));
        try{
            ResultSet pass = db.runQuery("SELECT password FROM pengguna WHERE id_pengguna = '"
                                        +(String) t_data.getValueAt(t_data.getSelectedRow(), 0)+"'");
            if(pass.next()) this._pass_lama = pass.getString(1);
        } catch (SQLException err) {koneksi.print(err.getMessage());}
        
    }//GEN-LAST:event_t_dataMouseClicked

    private void f_id_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_id_penggunaActionPerformed
        this.no_user();
    }//GEN-LAST:event_f_id_penggunaActionPerformed

    private void f_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_passwordActionPerformed
        if(l_pass_1.getText().equals("Ganti Password Lama")){
            try {
                ResultSet pass = db.runQuery("SELECT * FROM pengguna WHERE password = '"
                                            + f_password.getText().toLowerCase().trim() +"' "
                                            + "AND id_pengguna = '"+f_id_pengguna.getText()+"'");
                if(pass.next()) {
                    f_password.setEnabled(false); f_password_verify.requestFocus();
                    l_pass_2.setText("Password Baru");
                } else koneksi.popup_message("Password lama tidak cocok!");
            } catch (SQLException err) {koneksi.print(err.getMessage());}
        }
    }//GEN-LAST:event_f_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Menu_Pengguna dialog = new Menu_Pengguna();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_batal;
    private javax.swing.JButton b_process;
    private javax.swing.JComboBox<String> c_jabatan;
    private javax.swing.JTextField f_cari;
    private javax.swing.JTextField f_id_pengguna;
    private javax.swing.JTextField f_nama;
    private javax.swing.JPasswordField f_password;
    private javax.swing.JPasswordField f_password_verify;
    private javax.swing.JTextField f_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l_ket;
    private javax.swing.JLabel l_pass_1;
    private javax.swing.JLabel l_pass_2;
    private javax.swing.JTable t_data;
    // End of variables declaration//GEN-END:variables

    
    // PUBLIC CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    public void grant_permission(Boolean _grant){
        this._is_grant = _grant;
    }
    
    //---------------------------------------------------------------------------------//
    
    public void get_user(String _username){
        this._user = _username;
    }
    
    
    
    
    // PROTECTED CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    protected void _check_permission(){
        if(this._is_grant.equals(false)) {
            
            koneksi.popup_message("Anda tidak memiliki izin!");
            this.dispose();
            
        }
    }
    
    //---------------------------------------------------------------------------------//
    
    protected void _check_user(String _user){
        try {
            ResultSet result = db.runQuery("SELECT username FROM pengguna WHERE username = '"+_user+"'");
            if (result.next()) koneksi.popup_message("'"+_user+"' telah terdaftar!");
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
    }
    
    
    
    
    
    // PRIVATE CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    private void no_user(){
        String urut = null;
        this._query = "SELECT RIGHT(id_pengguna, 3) + 1 FROM pengguna ORDER BY id_pengguna";
        try {
            ResultSet id = db.runQuery(_query);
            if(id.last()){
                if(id.getInt(1) < 9) urut = "P00"+id.getString(1);
                else if(id.getInt(1) < 99) urut = "P0"+id.getString(1);
                else if(id.getInt(1) < 999) urut = "P"+id.getString(1);
            }
            f_id_pengguna.setText(urut);
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
    }
    
    //---------------------------------------------------------------------------------//
    
    private void create_user(){
        if(this.check_user()){
            this._query = "INSERT INTO pengguna(id_pengguna, username, nama_pengguna, password, jabatan) VALUES('"
                    + f_id_pengguna.getText().toUpperCase().trim()+"', '"
                    + f_username.getText().toLowerCase().trim() +"', '"
                    + f_nama.getText().toLowerCase().trim() +"', '"
                    + f_password.getText().toLowerCase().trim() +"', '"
                    + c_jabatan.getSelectedItem().toString().trim() +"')";
            try {
                db.runQueryUpdate(_query);
                koneksi.popup_message("Pengguna berhasil di simpan!");
            } catch (SQLException err) { koneksi.print(err.getMessage()); }
            
        } else koneksi.popup_message("Pengguna telah terdaftar!");
        
    }
    
    //---------------------------------------------------------------------------------//
    
    private Boolean check_user(){
        try {
            ResultSet check = db.runQuery("SELECT id_pengguna FROM pengguna WHERE id_pengguna = '"+f_id_pengguna.getText()+"' "
                                        + "OR username = '"+f_username.getText()+"'");
            if(check.next()) return false;
        } catch (SQLException err){ koneksi.print(err.getMessage()); }
        
        return true;
    }
    
    //---------------------------------------------------------------------------------//
    
    private void update_user(){
        String pass = null;
        if(l_pass_2.getText().equals("Verifikasi Password")){
                        
            if(f_password_verify.getText().equals(this._pass_lama)){
                pass = this._pass_lama.toLowerCase().trim();
            } else koneksi.popup_message("Password verifikasi tidak cocok!");
            
        } else if (l_pass_2.getText().equals("Password Baru")){
            pass = f_password_verify.getText().toLowerCase().trim();
        }
        
        this._query = "UPDATE pengguna SET nama_pengguna = '"+ f_nama.getText().toLowerCase().trim() +"', "
                    + "password = '"+ pass +"', jabatan = '"+ c_jabatan.getSelectedItem().toString().trim() +"', "
                    + "username  = '"+ f_username.getText().toLowerCase().trim() +"' "
                    + "WHERE id_pengguna  = '"+ f_id_pengguna.getText().toUpperCase().trim() +"'";
        
        try {
            db.runQueryUpdate(_query);
            
            koneksi.popup_message("Pengguna '"+f_nama.getText()+"' berhasil di update!");
            try {
                ResultSet check = db.runQuery("SELECT jabatan FROM pengguna WHERE username = '"+this._user+"'");
                if(check.next() && !check.getString(1).equals("Admin")){
                    koneksi.popup_message("Halaman ini hanya untuk admin!");
                    Autentikasi.Login portal = new Autentikasi.Login();
                    portal.setLocationRelativeTo(null);
                    portal.setVisible(true);
                }
            } catch (SQLException err) { koneksi.print(err.getMessage()); }
            
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
    }
    
    //---------------------------------------------------------------------------------//
    
    private void get_data_table(){
        final String[] _label = {"ID Pengguna", "Username", "Nama", "Password", "Jabatan"};
        try{
            
            ResultSet result = db.runQuery("SELECT * FROM pengguna");
            ResultSetMetaData table = result.getMetaData();
            int _row = 0, counter = 0; while (result.next()) _row = result.getRow();
            
            Object[][] _data = new Object[_row][table.getColumnCount()];
            result.beforeFirst();
            
            while(result.next()){
                _data[counter][0] = result.getString(1);
                _data[counter][1] = result.getString(2);
                _data[counter][2] = result.getString(3);
                _data[counter][3] = result.getString(4).replaceAll("[a-zA-Z0-9]", "*");
                _data[counter][4] = result.getString(5);
                counter++;
            }
            
            t_data.setModel( new javax.swing.table.DefaultTableModel(_data, _label));
            
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
    }
    
    //---------------------------------------------------------------------------------//
    
    private void search_data_table(){
        final String[] _label = {"ID Pengguna", "Username", "Nama", "Password", "Jabatan"};
        try{
            
            ResultSet result = db.runQuery("SELECT * FROM pengguna WHERE username LIKE '%"+f_cari.getText()+"%'");
            ResultSetMetaData table = result.getMetaData();
            int _row = 0, counter = 0; while (result.next()) _row = result.getRow();
            
            Object[][] _data = new Object[_row][table.getColumnCount()];
            result.beforeFirst();
            
            while(result.next()){
                _data[counter][0] = result.getString(1);
                _data[counter][1] = result.getString(2);
                _data[counter][2] = result.getString(3);
                _data[counter][3] = result.getString(4).replaceAll("[a-zA-Z0-9]", "*");
                _data[counter][4] = result.getString(5);
                counter++;
            }
            
            t_data.setModel( new javax.swing.table.DefaultTableModel(_data, _label));
            
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
    }
    
    //---------------------------------------------------------------------------------//
    
    private Boolean field_validation(){
        javax.swing.JTextField[] _fields = {f_id_pengguna, f_username, f_nama};
        for(javax.swing.JTextField _field : _fields){
            if(_field.getText().isEmpty()){
                koneksi.popup_message("Data Belum lengkap");
                return false;
            }
        }
        return true;
    }
    
    
    
    
    
    // END OF CLASS DECLARATION
}
