/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Keuangan;

import javax.swing.JOptionPane;
import Config.koneksi;
import java.sql.*;

/**
 *
 * @author Muhammad Iqbal
 */
public class Menu_Pembentukan extends javax.swing.JDialog {

    koneksi db = new koneksi();

    protected int _sisa_saldo = 0;
    protected String _query, _keterangan_pengisian;
    protected Boolean _is_grant = false;

    /**
     * Creates new form Menu_Pembentukan
     */
    public Menu_Pembentukan() {
        initComponents();
        b_process.setEnabled(false);
        b_cancel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        f_no_pengisian = new javax.swing.JTextField();
        f_tanggal = new javax.swing.JTextField();
        f_jumlah = new javax.swing.JTextField();
        f_terpakai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        f_uraian = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        f_pengisian_kembali = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_data_pengisian = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        b_process = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("APLIKASI KAS KACIL - PT. Exlayer Teknologi Indonesia | Pembentukan & Pengisian Kembali Saldo Awal Kas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(2, 47, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xlayer_logo.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(2, 47, 102));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pembentukan Dana Kas Kecil");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aplikasi Kas Kecil");

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PT. Exlayer Teknologi Indonesia \t\t\t\t\t\t\t ");

        jPanel8.setBackground(new java.awt.Color(2, 47, 102));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_map_white_18pt.png"))); // NOI18N
        jLabel27.setText("Alamat");

        jLabel28.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Intiland Tower - Annex, 8th Floor. Jl. Jend. Sudirman Kav 32, Jakarta 10220");

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_phone_white_18pt.png"))); // NOI18N
        jLabel29.setText("Telepon");

        jLabel30.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("(021) -57853468 ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(12, 12, 12)
                .addComponent(jLabel29)
                .addGap(10, 10, 10)
                .addComponent(jLabel30))
        );

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(118, 118, 118)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(jSeparator3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(2, 47, 102));

        f_no_pengisian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_no_pengisianActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No. Pengisian");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jumlah Nominal");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Terpakai");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Uraian Pengisian");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ENTER");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pengisian Kembali");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(f_no_pengisian, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(f_tanggal))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(f_jumlah))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(f_terpakai, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(f_uraian, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(f_pengisian_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_no_pengisian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_terpakai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(f_uraian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_pengisian_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(2, 47, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null), "Data Pembentukan & Pengisian Dana Kas Kecil", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        t_data_pengisian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_data_pengisian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_data_pengisianMouseClicked(evt);
            }
        });
        t_data_pengisian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_data_pengisianKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(t_data_pengisian);

        jLabel20.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("*Note : Tekan Tombol ' DELETE' untuk menghapus data");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        b_process.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_save_18pt.png"))); // NOI18N
        b_process.setText("Simpan");
        b_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_processActionPerformed(evt);
            }
        });

        b_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_clear_18pt.png"))); // NOI18N
        b_cancel.setText("Batal");
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_process, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_process, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_no_pengisianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_no_pengisianActionPerformed
        this.set_no_pengisian();
        f_jumlah.requestFocus();
        b_process.setEnabled(true);
        b_cancel.setEnabled(true);
        try {
            db.runQueryUpdate("INSERT INTO pembentukan_dana (no_pengisian) VALUES ('" + f_no_pengisian.getText() + "')");
        } catch (SQLException err) {
            koneksi.print(err.getMessage());
        }
        b_cancel.setText("Batal");
    }//GEN-LAST:event_f_no_pengisianActionPerformed

    private void b_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_processActionPerformed
        if (this.field_validation()) {
            switch (b_process.getText()) {
                case "Simpan":
                    this.save_pengisian();
                    break;

                case "Simpan Perubahan":
                    this.edit_pengisian();
                    b_process.setText("Simpan");
                    break;
            }

            b_process.setEnabled(false);
            b_cancel.setEnabled(false);
        }
    }//GEN-LAST:event_b_processActionPerformed

    private void t_data_pengisianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_data_pengisianMouseClicked
        b_process.setEnabled(true);
        b_cancel.setEnabled(true);
        b_cancel.setText("Kembali");
        b_process.setText("Simpan Perubahan");

        f_no_pengisian.setText((String) t_data_pengisian.getValueAt(t_data_pengisian.getSelectedRow(), 0));
        f_tanggal.setText((String) t_data_pengisian.getValueAt(t_data_pengisian.getSelectedRow(), 1));
        f_jumlah.setText((String) t_data_pengisian.getValueAt(t_data_pengisian.getSelectedRow(), 2));
        f_terpakai.setText((String) t_data_pengisian.getValueAt(t_data_pengisian.getSelectedRow(), 3));
        this._keterangan_pengisian = (String) t_data_pengisian.getValueAt(t_data_pengisian.getSelectedRow(), 5);
        f_uraian.setText((String) t_data_pengisian.getValueAt(t_data_pengisian.getSelectedRow(), 6));
        f_pengisian_kembali.setText((String) t_data_pengisian.getValueAt(t_data_pengisian.getSelectedRow(), 8));
    }//GEN-LAST:event_t_data_pengisianMouseClicked

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        if (b_cancel.getText().equals("Kembali")) {
            b_cancel.setText("Batal");
            b_process.setText("Simpan");
            t_data_pengisian.clearSelection();
            this.clear();
        } else {
            this.cancel_pengisian();
            b_process.setEnabled(false);
            b_cancel.setEnabled(false);
        }

    }//GEN-LAST:event_b_cancelActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//        this._check_permission();
        this.get_data_table();
    }//GEN-LAST:event_formWindowActivated

    private void t_data_pengisianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_data_pengisianKeyPressed
        this.delete_pengisian();
    }//GEN-LAST:event_t_data_pengisianKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Pembentukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Menu_Pembentukan dialog = new Menu_Pembentukan();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_process;
    private javax.swing.JTextField f_jumlah;
    private javax.swing.JTextField f_no_pengisian;
    private javax.swing.JTextField f_pengisian_kembali;
    private javax.swing.JTextField f_tanggal;
    private javax.swing.JTextField f_terpakai;
    private javax.swing.JTextField f_uraian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable t_data_pengisian;
    // End of variables declaration//GEN-END:variables

    // PUBLIC CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    public void grant_permission(Boolean _grant) {
        this._is_grant = _grant;
    }

    // PROTECTED CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    protected void _check_permission() {
        if (this._is_grant.equals(false)) {

            koneksi.popup_message("Anda tidak memiliki izin!");
            this.dispose();

        }
    }

    //---------------------------------------------------------------------------------//
    protected Boolean field_validation() {
        javax.swing.JTextField[] _fields = {f_no_pengisian, f_tanggal, f_uraian, f_jumlah};
        for (javax.swing.JTextField _field : _fields) {
            if (_field.getText().isEmpty()) {
                koneksi.popup_message("Data Belum Lengkap!");
                return false;
            } else if (f_jumlah.getText().isEmpty() && f_terpakai.getText().isEmpty()) {
                koneksi.popup_message("Data Belum Lengkap!");
                return false;
            }
        }

        return true;
    }

    // PRIVATE CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    private void set_no_pengisian() {
        String no_pengisian = null, no_urut = null;
        this._query = "SELECT RIGHT(no_pengisian, 3) + 1 FROM pembentukan_dana ORDER BY no_pengisian";
        try {
            ResultSet result = db.runQuery(this._query);
            if (result.next()) {
                result.last();

                if (result.getInt(1) <= 9) {
                    no_urut = "/00" + result.getString(1);
                } else if (result.getInt(1) <= 99) {
                    no_urut = "/0" + result.getString(1);
                } else {
                    no_urut = result.getString(1);
                }

                no_pengisian = "PBK" + koneksi.get_date_with_format("/YY/MM") + no_urut;
            } else {
                no_pengisian = "PBK" + koneksi.get_date_with_format("/YY/MM/") + "001";
            }
        } catch (SQLException err) {
            koneksi.print(err.getMessage());
        }

        f_no_pengisian.setText(no_pengisian);
        f_tanggal.setText(koneksi.get_date_with_format("YYYY-MM-dd"));

        int value = Integer.parseInt(koneksi.get_date_with_format("dd"));

        final String[] keterangan_pengisian = {"Minggu Pertama", "Minggu Kedua",
            "Minggu Ketiga", "Minggu Keempat"};
        int[] _days = {8, 15, 22, 28};

        for (int i = 0; i < _days.length; i++) {
            if (value < _days[i]) {
                this._keterangan_pengisian = keterangan_pengisian[i];
                break;
            } else if (value >= _days[3]) {
                this._keterangan_pengisian = keterangan_pengisian[3];
                break;
            }
        }
    }

    //---------------------------------------------------------------------------------//
    private void get_data_table() {
        final String[] _label = {"No. Pengisian", "Tanggal", "Jumlah", "Terpakai", "Sisa Saldo", "Periode", "Uraian Pembentukan", "Transaksi Terakhir",
            "Pengisian Kembali", "Tanggal Pengisian Kembali"};
        try {
            this._query = "SELECT * FROM pembentukan_dana ORDER BY no_pengisian";
            ResultSet result = db.runQuery(_query);
            ResultSetMetaData table = result.getMetaData();

            int _row = 0, counter = 0;
            while (result.next()) {
                _row = result.getRow();
            }
            Object[][] data_pembentukan = new Object[_row][table.getColumnCount()+1];
            result.beforeFirst();
            while (result.next()) {
                for(int i = 0; i < table.getColumnCount(); i++) data_pembentukan[counter][i] = result.getString(i+1);
                counter++;
            }
            t_data_pengisian.setModel(new javax.swing.table.DefaultTableModel(data_pembentukan, _label));
        } catch (SQLException err) {
            koneksi.print(err.getMessage());
        }
    }

    //---------------------------------------------------------------------------------//
    private void save_pengisian() {
        
        int terpakai = 0, pengisian_kembali = 0;
        int jumlah = Integer.parseInt(f_jumlah.getText());
        
        if(!f_terpakai.getText().isEmpty()){ terpakai = Integer.parseInt(f_terpakai.getText()); }
        if(!f_pengisian_kembali.getText().isEmpty()){ pengisian_kembali = Integer.parseInt(f_pengisian_kembali.getText()); }

        int sisa_saldo = ( jumlah + pengisian_kembali ) - terpakai;

        if (f_pengisian_kembali.getText().isEmpty() || f_pengisian_kembali.getText().equals("0")) {
            this._query = "UPDATE pembentukan_dana SET "
                    + "tanggal_pembentukan = '" + f_tanggal.getText() + "', "
                    + "jumlah = " + f_jumlah.getText() + ", "
                    + "terpakai = " + terpakai + ", "
                    + "sisa_saldo = "+sisa_saldo+", "
                    + "keterangan_periode = '" + this._keterangan_pengisian + "', "
                    + "uraian_pembentukan = '" + f_uraian.getText() + "', "
                    + "jumlah_pengisian_kembali = 0, "
                    + "tanggal_pengisian_kembali = NULL "
                    + "WHERE no_pengisian = '" + f_no_pengisian.getText() + "'";
        } else {
            this._query = "UPDATE pembentukan_dana SET "
                    + "tanggal_pembentukan = '" + f_tanggal.getText() + "', "
                    + "jumlah = " + f_jumlah.getText() + ", "
                    + "terpakai = " + terpakai + ", "
                    + "sisa_saldo = "+ sisa_saldo +", "
                    + "keterangan_periode = '" + this._keterangan_pengisian + "', "
                    + "uraian_pembentukan = '" + f_uraian.getText() + "', "
                    + "jumlah_pengisian_kembali = " + f_pengisian_kembali.getText() + ", "
                    + "tanggal_pengisian_kembali = '" + koneksi.get_date_with_format("YYYY-MM-dd HH:mm:dd") + "' "
                    + "WHERE no_pengisian = '" + f_no_pengisian.getText() + "'";
        }

        try {
            int jumlah_awal = Integer.parseInt(f_jumlah.getText()),
                    terpakai_awal = 0,
                    pengisian_kembali_awal = 0;

            if (!f_terpakai.getText().isEmpty()) {
                terpakai_awal = Integer.parseInt(f_terpakai.getText());
            }
            if (!f_pengisian_kembali.getText().isEmpty()) {
                pengisian_kembali_awal = Integer.parseInt(f_pengisian_kembali.getText());
            }

            int total = jumlah_awal + pengisian_kembali_awal;

            if (total >= terpakai_awal) {
                db.runQueryUpdate(_query);
                koneksi.popup_message("Berhasil di simpan");
            } else {
                koneksi.popup_message("Jumlah terpakai tidak sesuai dengan dana perusahaan!");
            }

        } catch (SQLException err) {
            koneksi.print(err.getMessage());
        }

        this.get_data_table();
        this.clear();
    }

    //---------------------------------------------------------------------------------//
    private void edit_pengisian() {

        int terpakai = 0, jumlah = 0, pengisian_kembali = 0;
        if(!f_terpakai.getText().isEmpty()){ terpakai = Integer.parseInt(f_terpakai.getText()); }
        if(!f_jumlah.getText().isEmpty()){ jumlah = Integer.parseInt(f_jumlah.getText()); }
        if(!f_pengisian_kembali.getText().isEmpty()){ pengisian_kembali = Integer.parseInt(f_pengisian_kembali.getText()); }

        int sisa_saldo = ( jumlah + pengisian_kembali ) - terpakai;
        
        if (f_pengisian_kembali.getText().isEmpty() || f_pengisian_kembali.getText().equals("0")) {
            this._query = "UPDATE pembentukan_dana SET "
                    + "tanggal_pembentukan = '" + f_tanggal.getText() + "', "
                    + "jumlah = " + f_jumlah.getText() + ", "
                    + "terpakai = " + terpakai + ", "
                    + "sisa_saldo = "+sisa_saldo+", "
                    + "keterangan_periode = '" + this._keterangan_pengisian + "', "
                    + "uraian_pembentukan = '" + f_uraian.getText() + "', "
                    + "jumlah_pengisian_kembali = 0, "
                    + "tanggal_pengisian_kembali = NULL "
                    + "WHERE no_pengisian = '" + f_no_pengisian.getText() + "'";
        } else {
            this._query = "UPDATE pembentukan_dana SET "
                    + "tanggal_pembentukan = '" + f_tanggal.getText() + "', "
                    + "jumlah = " + f_jumlah.getText() + ", "
                    + "terpakai = " + terpakai + ", "
                    + "sisa_saldo = "+sisa_saldo+", "
                    + "keterangan_periode = '" + this._keterangan_pengisian + "', "
                    + "uraian_pembentukan = '" + f_uraian.getText() + "', "
                    + "jumlah_pengisian_kembali = " + f_pengisian_kembali.getText() + ", "
                    + "tanggal_pengisian_kembali = '" + koneksi.get_date_with_format("YYYY-MM-dd HH:mm:dd") + "' "
                    + "WHERE no_pengisian = '" + f_no_pengisian.getText() + "'";
        }

        try {
            int jumlah_awal = Integer.parseInt(f_jumlah.getText()),
                    terpakai_awal = 0,
                    pengisian_kembali_awal = 0;

            if (!f_terpakai.getText().isEmpty()) {
                terpakai_awal = Integer.parseInt(f_terpakai.getText());
            }
            
            if (!f_pengisian_kembali.getText().isEmpty()) {
                pengisian_kembali_awal = Integer.parseInt(f_pengisian_kembali.getText());
            }

            int total = jumlah_awal + pengisian_kembali_awal;

            if (total >= terpakai_awal) {
                db.runQueryUpdate(_query);
                koneksi.popup_message("Berhasil di simpan");
            } else {
                koneksi.popup_message("Jumlah terpakai tidak sesuai dengan dana perusahaan!");
            }

        } catch (SQLException err) {
            koneksi.print(err.getMessage());
        }

        this.get_data_table();
        this.clear();
    }

    //---------------------------------------------------------------------------------//
//    private void check_sisa_saldo(){
//        
//        int jumlah = 0, terpakai = 0, pengisian_kembali = 0;
//        
//        if(t_data_pengisian.getRowCount() != 0){
//            
//            jumlah = Integer.parseInt((String) t_data_pengisian.getValueAt(t_data_pengisian.getRowCount() - 1, 2));
//            terpakai = Integer.parseInt((String) t_data_pengisian.getValueAt(t_data_pengisian.getRowCount() - 1, 3));
//            pengisian_kembali = Integer.parseInt((String) t_data_pengisian.getValueAt(t_data_pengisian.getRowCount() - 1, 7));
//            
//            this._sisa_saldo = ( jumlah + pengisian_kembali ) - terpakai;
//        }
//    }
    //---------------------------------------------------------------------------------//
    private void delete_pengisian() {
        int konfir = JOptionPane.showConfirmDialog(this,
                "Apa Anda Yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (konfir == JOptionPane.YES_OPTION) {
            try {
                ResultSet check = db.runQuery("SELECT terpakai FROM pembentukan_dana WHERE no_pengisian = '" + f_no_pengisian.getText() + "'");
                if (check.next()) {
                    if (check.getInt(1) > 0) {
                        koneksi.popup_message("Data sedang di gunakan mohon check data transaksi!");
                    } else {
                        db.runQueryUpdate("DELETE FROM pembentukan_dana "
                                + "WHERE no_pengisian = '" + f_no_pengisian.getText() + "'");
                        koneksi.popup_message("Berhasil di hapus");
                        b_process.setText("Simpan");
                        b_cancel.setText("Batal");
                    }
                }
            } catch (SQLException err) {
                koneksi.print(err.getMessage());
            }
            this.get_data_table();
            this.clear();
        }
    }

    //---------------------------------------------------------------------------------//
    private void cancel_pengisian() {
        try {
            db.runQueryUpdate("DELETE FROM pembentukan_dana "
                    + "WHERE no_pengisian = '" + f_no_pengisian.getText() + "'");
        } catch (SQLException err) {
            koneksi.print(err.getMessage());
        }
        this.get_data_table();
        this.clear();
    }

    //---------------------------------------------------------------------------------//
    
    private void clear() {
        f_no_pengisian.setText(null);
        f_tanggal.setText(null);
        f_jumlah.setText(null);
        f_terpakai.setText(null);
        f_uraian.setText(null);
        f_pengisian_kembali.setText(null);
    }

    // END OF CLASS DECLARATION
}
