/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Keuangan;

import Config.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Iqbal
 */
public class Menu_Pengeluaran extends javax.swing.JDialog {

    koneksi db = new koneksi();
    
    protected String _query, _no_pengisian, _id_pengguna, _id_pengajuan;
    protected Boolean _is_grant = false;
    protected int _used_balance = 0;
    
    public String id_kategori, no_rekening, keterangan;
    
    /**
     * Creates new form Menu_Pengeluaran
     */
    public Menu_Pengeluaran() {
        initComponents();
        this.field_enabled(false);
        this.set_nota_combobox();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        f_kode_transaksi = new javax.swing.JTextField();
        f_no_pengisian = new javax.swing.JTextField();
        f_tanggal_transaksi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        f_no_rekening = new javax.swing.JTextField();
        f_uraian = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        f_nominal = new javax.swing.JTextField();
        b_simpan = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        f_id_barang = new javax.swing.JTextField();
        b_cari = new javax.swing.JButton();
        f_keterangan_rek = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        f_id_pengajuan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_data_nota = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_data_transaksi = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        c_no_nota = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        l_id_pengguna = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("APLIKASI KAS KACIL - PT. Exlayer Teknologi Indonesia | Pengeluaran Dana Kas Kecil");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(2, 47, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xlayer_logo.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(2, 47, 102));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pengeluaran Dana Kas Kecil");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aplikasi Kas Kecil");

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PT. Exlayer Teknologi Indonesia \t\t\t\t\t\t\t ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(2, 47, 102));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kode Transaksi");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Pengisian");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Transaksi");

        f_kode_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_kode_transaksiActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No. Kategori");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Uraian");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nominal");

        b_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_save_18pt.png"))); // NOI18N
        b_simpan.setText("Simpan");
        b_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanActionPerformed(evt);
            }
        });

        b_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_clear_18pt.png"))); // NOI18N
        b_cancel.setText("Batal");
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ENTER");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Kategori");

        b_cari.setText("Cari");
        b_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cariActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ID Pengajuan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f_no_pengisian)
                    .addComponent(f_tanggal_transaksi)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(f_kode_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f_id_pengajuan)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(f_id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(f_no_rekening, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f_keterangan_rek))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f_uraian, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_nominal)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(b_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(f_kode_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(f_nominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9)
                    .addComponent(f_id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(f_no_rekening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(f_keterangan_rek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(f_no_pengisian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(f_tanggal_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(f_id_pengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_uraian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(2, 47, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null), "Data Pembentukan Dana", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        t_data_nota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_data_nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_data_notaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_data_nota);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(2, 47, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null), "Data Pengeluaran", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        t_data_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_data_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_data_transaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t_data_transaksi);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Filter Berdasarkan No. Pengisian");

        c_no_nota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -" }));
        c_no_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_no_notaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_no_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(c_no_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(2, 47, 102));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_map_white_18pt.png"))); // NOI18N
        jLabel14.setText("Alamat");

        jLabel15.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Intiland Tower - Annex, 8th Floor. Jl. Jend. Sudirman Kav 32, Jakarta 10220");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_phone_white_18pt.png"))); // NOI18N
        jLabel16.setText("Telepon");

        jLabel17.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("(021) -57853468 ");

        l_id_pengguna.setForeground(new java.awt.Color(2, 47, 102));
        l_id_pengguna.setText("jLabel18");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_id_pengguna)
                        .addGap(88, 88, 88))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(l_id_pengguna))
                .addGap(10, 10, 10)
                .addComponent(jLabel17))
        );

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this._check_permission();
        this.get_data_table(); this.get_data_table_nota();
        f_id_barang.setEditable(false);
        f_no_rekening.setEditable(false);
        f_keterangan_rek.setEditable(false);
    }//GEN-LAST:event_formWindowActivated

    private void f_kode_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_kode_transaksiActionPerformed
        if(f_kode_transaksi.getText().isEmpty()){
            this.set_no_pengeluaran();
            try {
                db.runQueryUpdate("INSERT INTO pengeluaran_dana (kode_transaksi) VALUES ('"+f_kode_transaksi.getText()+"')");
            } catch (SQLException err) {koneksi.print(err.getMessage());}
            f_tanggal_transaksi.setText(koneksi.get_date_with_format("YYYY-MM-dd HH:mm:ss"));
            this.field_enabled(true);
            t_data_transaksi.setEnabled(false);
        } else koneksi.popup_message("Field harus kosong!");
        
    }//GEN-LAST:event_f_kode_transaksiActionPerformed

    private void t_data_notaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_data_notaMouseClicked
        if(!f_kode_transaksi.getText().isEmpty()){
            if(Integer.parseInt((String) t_data_nota.getValueAt(t_data_nota.getSelectedRow(), 5))  == 0){
                Notifikasi.Dana_Tidak_Cukup portal = new Notifikasi.Dana_Tidak_Cukup();
                portal.setLocationRelativeTo(null);
                portal.setVisible(true);
            } else {
                f_no_pengisian.setText((String) t_data_nota.getValueAt(t_data_nota.getSelectedRow(), 0));
            }
            
        } else {
            koneksi.popup_message("Kode transaksi tidak di temukan");
        }
    }//GEN-LAST:event_t_data_notaMouseClicked

    private void b_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanActionPerformed
        if(this.field_validation()){
            int saldo_awal = 0, saldo_terpakai = 0, sisa = 0;
                    
            try{
                ResultSet result = db.runQuery("SELECT jumlah, jumlah_pengisian_kembali, terpakai, sisa_saldo, terpakai FROM pembentukan_dana "
                          + "WHERE no_pengisian = '"+f_no_pengisian.getText()+"'");
                
                if(result.next()){
                    saldo_awal = result.getInt(1) + result.getInt(2); saldo_terpakai = result.getInt(3);
                    sisa = result.getInt(4);
                }
                
            } catch (SQLException err) {koneksi.print(err.getMessage());}

            int sum_balance = Integer.parseInt(f_nominal.getText()) + saldo_terpakai;
                        
            if (saldo_awal >= sum_balance){
                
                int sisa_saldo = sisa - Integer.parseInt(f_nominal.getText());
                
                try{
                    db.runQueryUpdate("UPDATE pembentukan_dana SET terpakai = "+sum_balance+", sisa_saldo = "+sisa_saldo+", "
                                    + "terakhir_digunakan = '"+koneksi.get_date_with_format("YYYY-MM-dd HH:mm:ss")+"' "
                                    + "WHERE no_pengisian = '"+f_no_pengisian.getText()+"'");
                    this.get_data_table_nota();
                } catch (SQLException err) {koneksi.print(err.getMessage());}
                this.save_transaksi();
            } else {
                Notifikasi.Dana_Tidak_Cukup portal = new Notifikasi.Dana_Tidak_Cukup();
                portal.setLocationRelativeTo(null);
                portal.setVisible(true);
                f_nominal.requestFocus();
            }
        }
        
    }//GEN-LAST:event_b_simpanActionPerformed

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        switch(b_cancel.getText()){
            case "Batal":
                this.cancel_pengeluaran();
                break;
            case "Hapus":
                this.delete_pengeluaran();
                b_cancel.setText("Batal");
                break;
        }
        t_data_transaksi.setEnabled(true);
        t_data_transaksi.clearSelection();
        t_data_nota.clearSelection();
        this.field_enabled(false);
    }//GEN-LAST:event_b_cancelActionPerformed

    private void b_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cariActionPerformed
        if(!f_kode_transaksi.getText().isEmpty()){
            Menu_Popup_Data_Pengajuan portal = new Menu_Popup_Data_Pengajuan();
            portal.grant_permission(true);
            portal.portal = this;
            portal.setVisible(true);
        } else {
            koneksi.popup_message("Kode transaksi tidak di temukan");
        }
    }//GEN-LAST:event_b_cariActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        f_id_barang.setText(this.id_kategori); f_no_rekening.setText(this.no_rekening);
        f_id_pengajuan.setText(this._id_pengajuan);
        if(this.no_rekening != null){
            try {
                ResultSet result = db.runQuery("SELECT keterangan_kategori FROM kategori_rekening "
                                + "WHERE no_kategori = '"+this.no_rekening+"'");
                if (result.next()) f_keterangan_rek.setText(result.getString(1));
            } catch (SQLException err) {koneksi.print(err.getMessage());}   
        }
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void t_data_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_data_transaksiMouseClicked
        f_kode_transaksi.setText((String) t_data_transaksi.getValueAt(t_data_transaksi.getSelectedRow(), 0));
        this._used_balance = Integer.parseInt((String) t_data_transaksi.getValueAt(t_data_transaksi.getSelectedRow(), 9));
        this._no_pengisian = (String) t_data_transaksi.getValueAt(t_data_transaksi.getSelectedRow(), 1);
        b_cancel.setText("Hapus");
    }//GEN-LAST:event_t_data_transaksiMouseClicked

    private void c_no_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_no_notaActionPerformed
        this.get_data_filtered_by_nota();
    }//GEN-LAST:event_c_no_notaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Menu_Pengeluaran dialog = new Menu_Pengeluaran();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_cari;
    private javax.swing.JButton b_simpan;
    private javax.swing.JComboBox<String> c_no_nota;
    private javax.swing.JTextField f_id_barang;
    private javax.swing.JTextField f_id_pengajuan;
    private javax.swing.JTextField f_keterangan_rek;
    private javax.swing.JTextField f_kode_transaksi;
    private javax.swing.JTextField f_no_pengisian;
    private javax.swing.JTextField f_no_rekening;
    private javax.swing.JTextField f_nominal;
    private javax.swing.JTextField f_tanggal_transaksi;
    private javax.swing.JTextField f_uraian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel l_id_pengguna;
    private javax.swing.JTable t_data_nota;
    private javax.swing.JTable t_data_transaksi;
    // End of variables declaration//GEN-END:variables
    
    
    // PUBLIC CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    public void grant_permission(Boolean _grant){
        this._is_grant = _grant;
    }
    
    //---------------------------------------------------------------------------------//
    
    public void id_pengguna(String _id){
        try {
            ResultSet check = db.runQuery("SELECT id_pengguna FROM pengguna WHERE username = '"+_id+"'");
            if(check.next()) l_id_pengguna.setText(check.getString(1));
        } catch (SQLException err) { koneksi.print(err.getMessage()); }
    }

    
    
    
    // PROTECTED CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    protected void _check_permission(){
        if(this._is_grant.equals(false)) {
            
            koneksi.popup_message("Anda tidak memiliki izin!");
            this.dispose();
            
        }
    }
    
    //---------------------------------------------------------------------------------//
    
    protected Boolean field_validation(){
        javax.swing.JTextField[] _fields = {f_kode_transaksi, f_no_pengisian, f_tanggal_transaksi, f_id_barang,
                                            f_no_rekening, f_keterangan_rek, f_uraian, f_nominal};
        
        for(javax.swing.JTextField _field : _fields){
            if (_field.getText().isEmpty()){
                koneksi.popup_message("Data Belum Lengkap!");
                return false;
            }
        }
        
        return true;
    }
    
    
    
    
    // PRIVATE CLASS
    //////////////////////////////////////////////////////////////////////////////////////
    private void set_no_pengeluaran(){
        String kode_transaksi = null;
        this._query = "SELECT RIGHT(`kode_transaksi`, 3) + 1 FROM pengeluaran_dana ORDER BY kode_transaksi";
        try {
            ResultSet result = db.runQuery(_query);
            if (result.last()){
                if(result.getInt(1) <= 9){
                   kode_transaksi = "TRX"+koneksi.get_date_with_format("/YY/MM/00")
                                +result.getString(1); 
                } else if (result.getInt(1) <= 99){
                    kode_transaksi = "TRX"+koneksi.get_date_with_format("/YY/MM/0")
                                +result.getString(1); 
                } else {
                    kode_transaksi = "TRX"+koneksi.get_date_with_format("/YY/MM/")
                                +result.getString(1); 
                }
            } else {
                kode_transaksi = "TRX"+koneksi.get_date_with_format("/YY/MM/")+"001";
            }
        } catch (SQLException err) {koneksi.print(err.getMessage());}
        f_kode_transaksi.setText(kode_transaksi);
    }
    
    //---------------------------------------------------------------------------------//
    
    private void set_nota_combobox(){
        try {
            ResultSet result = db.runQuery("SELECT no_pengisian FROM pembentukan_dana ORDER BY no_pengisian");
            while(result.next()) c_no_nota.addItem(result.getString(1));
        } catch (SQLException err) {koneksi.print(err.getMessage());}
    }
    
    //---------------------------------------------------------------------------------//r
    
    private void get_data_filtered_by_nota(){
        final String[] _label = {"Kode Transaksi", "No Pengisian", "ID Pengguna", "Tanggal", "ID Pengajuan", "ID Kategori", 
                                 "No. Kategori", "Keterangan Rekening", "Uraian" ,"Nominal"};
        
        String no_pengisian = null;
        
        if (c_no_nota.getSelectedIndex() > 0) {
            no_pengisian = (String) c_no_nota.getSelectedItem();
            
            try {
                this._query = "SELECT kode_transaksi, no_pengisian, id_pengguna, tanggal, id_pengajuan, id_kategori, "
                            + "no_kategori, keterangan_kategori, uraian_pengeluaran, nominal FROM pengeluaran_dana WHERE no_pengisian = '"+no_pengisian+"'";

                ResultSet result = db.runQuery(_query);
                ResultSetMetaData table = result.getMetaData();

                int _row = 0, counter = 0; while(result.next()){ _row = result.getRow(); }
                Object[][] data_nota = new Object[_row][table.getColumnCount()];
                result.beforeFirst();
                while(result.next()){
                    for(int i = 0; i < table.getColumnCount(); i++) data_nota[counter][i] = result.getString(i+1);
                    counter++;
                }
                t_data_transaksi.setModel(new javax.swing.table.DefaultTableModel(data_nota, _label));
            } catch (SQLException err) {koneksi.print(err.getMessage());}
            
        } else this.get_data_table_nota();
    }
    
    //---------------------------------------------------------------------------------//
    
    private void get_data_table(){
        final String[] _label = {"Kode Transaksi", "No Pengisian", "ID Pengguna", "Tanggal", "ID Pengajuan","ID Kategori", 
                                 "No. Kategori", "Keterangan Kategori", "Uraian" ,"Nominal"};
        try {
            this._query = "SELECT kode_transaksi, no_pengisian, id_pengguna, tanggal, id_pengajuan, id_kategori, "
                        + "no_kategori, keterangan_kategori, uraian_pengeluaran, nominal FROM pengeluaran_dana ORDER BY kode_transaksi";
            ResultSet result = db.runQuery(_query);
            ResultSetMetaData table = result.getMetaData();
            
            int _row = 0, counter = 0; while(result.next()){ _row = result.getRow(); }
            Object[][] data_pengeluaran = new Object[_row][table.getColumnCount()];
            result.beforeFirst();
            while(result.next()){
                for(int i = 0; i < table.getColumnCount(); i++) data_pengeluaran[counter][i] = result.getString(i+1);
                counter++;
            }
            t_data_transaksi.setModel(new javax.swing.table.DefaultTableModel(data_pengeluaran, _label));
        } catch (SQLException err) {koneksi.print(err.getMessage());}
    }
    
    //---------------------------------------------------------------------------------//
    
    private void get_data_table_nota(){
        final String[] _label = {"No Pengisian", "Tanggal", "Jumlah", "Terpakai", "Pengisian Kembali", "Sisa Saldo", "Uraian Pembentukan"};
        try {
            this._query = "SELECT no_pengisian, tanggal_pembentukan, jumlah, terpakai, jumlah_pengisian_kembali, sisa_saldo, uraian_pembentukan "
                        + "FROM pembentukan_dana WHERE tanggal_pembentukan LIKE '%"+koneksi.get_date_with_format("MM")+"%' ORDER BY no_pengisian";

            ResultSet result = db.runQuery(_query);
            ResultSetMetaData table = result.getMetaData();
            
            int _row = 0, counter = 0; while(result.next()){ _row = result.getRow(); }
            Object[][] data_pengisian = new Object[_row][table.getColumnCount()+1];
            result.beforeFirst();
            while(result.next()){
                for(int i = 0; i < table.getColumnCount(); i++) data_pengisian[counter][i] = result.getString(i+1);
                counter++;
            }
            t_data_nota.setModel(new javax.swing.table.DefaultTableModel(data_pengisian, _label));
        } catch (SQLException err) {koneksi.print(err.getMessage());}
    }
    
    //---------------------------------------------------------------------------------//
    
    private void save_transaksi(){
        koneksi.print(l_id_pengguna.getText());
        this._query = "UPDATE pengeluaran_dana SET "
                + "no_pengisian = '"+f_no_pengisian.getText()+"', "
                + "id_pengguna = '"+l_id_pengguna.getText()+"', "
                + "tanggal = '"+f_tanggal_transaksi.getText()+"', "
                + "id_pengajuan = '"+f_id_pengajuan.getText()+"', "
                + "id_kategori = "+f_id_barang.getText()+", "
                + "no_kategori = "+f_no_rekening.getText()+", "
                + "keterangan_kategori = '"+f_keterangan_rek.getText().trim()+"', "
                + "uraian_pengeluaran = '"+f_uraian.getText().trim()+"', "
                + "nominal = "+f_nominal.getText().trim()+" "
                + "WHERE kode_transaksi = '"+f_kode_transaksi.getText().trim()+"'";
        try {
            db.runQueryUpdate(_query);
            koneksi.popup_message("Berhasil di simpan");
        } catch (SQLException err) {koneksi.print(err.getMessage());}
        this.get_data_table();
        this.get_data_table_nota();
        this.clear();
        this.field_enabled(false);
        t_data_transaksi.setEnabled(true);
    }
    
    //---------------------------------------------------------------------------------//
    
    private void delete_pengeluaran(){
        int konfir = JOptionPane.showConfirmDialog(this, 
                    "Apa Anda Yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            
        if (konfir == JOptionPane.YES_OPTION){
            
            int default_balance = 0,
                sum_balance = 0,
                sisa = 0;
            
            try{
                
                ResultSet result = db.runQuery("SELECT terpakai, sisa_saldo FROM pembentukan_dana "
                          + "WHERE no_pengisian = '"+this._no_pengisian+"'");
                
                if(result.next()){
                    default_balance = result.getInt(1); sisa = result.getInt(2);
                }
                
                sum_balance = default_balance - this._used_balance;
                
                int sisa_saldo = this._used_balance + sisa;
                
                koneksi.print("sisa saldo = "+sisa_saldo);
                
                db.runQueryUpdate("UPDATE pembentukan_dana SET terpakai = "+sum_balance+", sisa_saldo = "+sisa_saldo+" "
                                 + "WHERE no_pengisian = '"+this._no_pengisian+"'");
                
                db.runQueryUpdate("DELETE FROM pengeluaran_dana "
                            + "WHERE kode_transaksi = '"+f_kode_transaksi.getText()+"'");
                
                koneksi.popup_message("'"+f_kode_transaksi.getText()+"' berhasil di hapus!");
                
                this._used_balance = 0;
                this._no_pengisian = null;
                
            } catch (SQLException err) {koneksi.print(err.getMessage());}
        }
        this.get_data_table();
        this.clear();
    }
    
    //---------------------------------------------------------------------------------//
    
    private void cancel_pengeluaran(){
        try {
            db.runQueryUpdate("DELETE FROM pengeluaran_dana "
                            + "WHERE kode_transaksi = '"+f_kode_transaksi.getText()+"'");
        } catch (SQLException err) {koneksi.print(err.getMessage());}
        this.get_data_table();
        this.clear();
    }
    
    //---------------------------------------------------------------------------------//
    
    private void clear(){
        this.id_kategori = null;
        this.no_rekening = null;
        this._id_pengajuan = null;
        f_kode_transaksi.setText(null);
        f_no_pengisian.setText(null);
        f_tanggal_transaksi.setText(null);
        f_id_pengajuan.setText(null);
        f_id_barang.setText(null);
        f_no_rekening.setText(null);
        f_keterangan_rek.setText(null);
        f_uraian.setText(null);
        f_nominal.setText(null);
    }
    
    //---------------------------------------------------------------------------------//
    
    private void field_enabled(Boolean _status){
        f_no_pengisian.setEnabled(_status);
        f_tanggal_transaksi.setEnabled(_status);
        f_id_barang.setEnabled(_status);
        f_id_pengajuan.setEnabled(_status);
        f_no_rekening.setEnabled(_status);
        f_keterangan_rek.setEnabled(_status);
        f_uraian.setEnabled(_status);
        f_nominal.setEnabled(_status);
        t_data_nota.setEnabled(_status);
        b_cari.setEnabled(_status);
    }
   
    
    
    
    
    // END OF CLASS DECLARATION
}
